[repository]
name = "pybr25-site"
managed_by_uv = true
changelog = "CHANGELOG.md"
version = "version.txt"
version_format = "calver"
container_images_prefix = "ghcr.io/pythonbrasil/pybr25-site"
compose = ["docker-compose.yml"]

[repository.towncrier]
section = "Project"
settings = "towncrier.toml"

[backend.package]
name = "pythonbrasil.site"
path = "backend"
code_path = "src/pythonbrasil/site"
changelog = "backend/CHANGELOG.md"
towncrier_settings = "backend/pyproject.toml"
base_package = "Products.CMFPlone"
publish = false

[frontend.package]
name = "volto-pythonbrasil-site"
path = "frontend/packages/volto-pythonbrasil-site"
code_path = "src"
changelog = "frontend/packages/volto-pythonbrasil-site/CHANGELOG.md"
towncrier_settings = "frontend/packages/volto-pythonbrasil-site/towncrier.toml"
base_package = "@plone/volto"
publish = false

[cookieplone]
template = "project"
template_version = "9d441519e682ed62e67b8c8d1fe531d7368af5da"
generated_date = "2025-04-24 19:16:37"
