name: PythonBrasil 2025 CI

on:
  push:
    paths:
      - "backend/**"
      - "frontend/**"
      - ".github/workflows/*.yml"
      - "devops/**"
  workflow_dispatch:

jobs:
  config:
    uses: ./.github/workflows/config.yml

  backend:
    uses: ./.github/workflows/backend.yml
    needs:
        - config
    with:
        base-tag: ${{ needs.config.outputs.base-tag }}
        image-name-prefix: ${{ needs.config.outputs.image-name-prefix }}
        image-name-suffix: backend
        python-version: ${{ needs.config.outputs.python-version }}
        plone-version: ${{ needs.config.outputs.plone-version }}
    if: ${{ needs.config.outputs.backend == 'true' }}
    permissions:
      contents: read
      packages: write

  frontend:
    uses: ./.github/workflows/frontend.yml
    needs:
        - config
    with:
        base-tag: ${{ needs.config.outputs.base-tag }}
        image-name-prefix: ${{ needs.config.outputs.image-name-prefix }}
        image-name-suffix: frontend
        node-version: ${{ needs.config.outputs.node-version }}
        volto-version: ${{ needs.config.outputs.volto-version }}
    if: ${{ needs.config.outputs.frontend == 'true' }}
    permissions:
      contents: read
      packages: write

  varnish:
    uses: ./.github/workflows/varnish.yml
    needs:
        - config
    with:
        base-tag: ${{ needs.config.outputs.base-tag }}
        image-name-prefix: ${{ needs.config.outputs.image-name-prefix }}
        image-name-suffix: varnish
    if: ${{ needs.config.outputs.varnish == 'true' }}
    permissions:
      contents: read
      packages: write
